# Generated by Django 4.0.3 on 2026-02-01 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_portal', '0010_alter_customer_id_alter_orders_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='customer_address',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='orders',
            name='customer_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='orders',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='orders',
            name='is_pending',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='orders',
            name='payment_method',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='orders',
            name='payment_proof',
            field=models.ImageField(blank=True, null=True, upload_to='payment_proofs/'),
        ),
        migrations.AddField(
            model_name='orders',
            name='rental_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='orders',
            name='return_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='rent',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='rentaldetails',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
